import FooterComponent from '@/components/FooterComponent'
import './../../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBarComponent from '@/components/NavBarComponent'
import ProductContextProvider from '@/components/context/ProductContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='overflowx-hidden'>
      <body className={inter.className}>
        <ProductContextProvider>
          <NavBarComponent />
          {children}
          <FooterComponent />
        </ProductContextProvider>
      </body>
    </html>
  )
}
